print("--------------------------------------------------------------")
print() # Add an empty line (the same as '\n' in a string)
print("What's your name? ")
name = input()
print()
print("Nice to see you "+name+"!")
print()